---
abstract: 'Simple definition language for rules'
author:
  - 'Peter Stuifzand E<lt>peter@stuifzand.euE<gt>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MarpaX-Simple-Rules
provides:
  MarpaX::Simple::Rules:
    file: lib/MarpaX/Simple/Rules.pm
    version: v0.2.4
requires:
  Marpa::XS: 1.0
resources:
  license: http://dev.perl.org/licenses/
version: v0.2.4
